apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: drizzy0606/auth-service:b5611a6063f68db6bd526991be9fcecd7c4ee6f0
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "mydb"
            - name: DATABASE_URL
              value: "postgresql://myuser:mypassword@postgres:5432/mydb"
          envFrom:
            - configMapRef:
                name: blog-service-config
            - secretRef:
                name: services-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
